<?xml version="1.0"?>
<robot name="mobile_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">
    
    <!--Wymiary robota-->
    <xacro:property name="bodyWidth" value="0.4"/>
    <xacro:property name="bodyLength" value="0.6"/>
    <xacro:property name="bodyHeight" value="0.2"/>
    <xacro:property name="wheelRadius" value="0.1"/>
    <xacro:property name="castorWheelRadius" value="0.05"/>

    <!--Kolory-->
    <material name="red">
        <color rgba="0.8 0.0 0.0 1.0"/>
    </material>
    <material name="blue">
        <color rgba="0.0 0.0 0.8 0.75"/>
    </material>
    <material name="green">
        <color rgba="0.0 0.8 0.0 1.0"/>
    </material>

    <!--Makro do inercji-->
    <xacro:macro name="default_inertial" params="mass">
        <inertial>
            <mass value="${mass}" />
            <inertia ixx="1e-3" ixy="0.0" ixz="0.0" iyy="1e-3" iyz="0.0" izz="1e-3" />
        </inertial>
    </xacro:macro>

    <!--Bryła robota-->
    <link name="body">
        <visual>
            <origin xyz="-${bodyLength/2} 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${bodyLength} ${bodyWidth} ${bodyHeight}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <origin xyz="-${bodyLength/2} 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${bodyLength} ${bodyWidth} ${bodyHeight}"/>
            </geometry>
        </collision>
        <xacro:default_inertial mass="2.0"/>
    </link>

    <!--Lewe koło-->
    <link name="left_wheel">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheelRadius}" length="0.05"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheelRadius}" length="0.05"/>
            </geometry>
        </collision>
        <xacro:default_inertial mass="0.15"/>
    </link>
    <joint name="left_wheel_joint" type="continuous">
        <parent link="body"/>
        <child link="left_wheel"/>
        <origin xyz="-${bodyLength -0.1} ${bodyWidth/2} -${bodyHeight/2-0.05}" rpy="0.0 0.0 0.0"/>
        <axis xyz="0.0 1.0 0.0"/>
        <limit effort="100" velocity="10.0"/>
        <dynamics damping="0.1" friction="0.1"/>
    </joint>

    <!--Prawe koło-->
    <link name="right_wheel">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheelRadius}" length="0.05"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheelRadius}" length="0.05"/>
            </geometry>
        </collision>
        <xacro:default_inertial mass="0.15"/>
    </link>
    <joint name="right_wheel_joint" type="continuous">
        <parent link="body"/>
        <child link="right_wheel"/>
        <origin xyz="-${bodyLength -0.1} -${bodyWidth/2} -${bodyHeight/2-0.05}" rpy="0.0 0.0 0.0"/>
        <axis xyz="0.0 1.0 0.0"/>
        <limit effort="100" velocity="10.0"/>
        <dynamics damping="0.1" friction="0.1"/>
    </joint>

    <!--Przednie koło-->
    <link name="castor_wheel">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <sphere radius="${castorWheelRadius}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <sphere radius="${castorWheelRadius}"/>
            </geometry>
        </collision>
        <xacro:default_inertial mass="0.1"/>
    </link>
    <joint name="castor_wheel_joint" type="fixed">
        <parent link="body"/>
        <child link="castor_wheel"/>
        <origin xyz="-0.05 0.0 -${bodyHeight/2}" rpy="0.0 0.0 0.0"/>
    </joint>

    <!--LIDAR-->
    <link name="lidar">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="0.1" length="0.1"/>
            </geometry>
            <material name="green"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="0.1" length="0.1"/>
            </geometry>
        </collision>
        <xacro:default_inertial mass="0.5"/>
    </link>
    <joint name="lidar_joint" type="fixed">
        <parent link="body"/>
        <child link="lidar"/>
        <origin xyz="-${bodyLength/2} 0.0 ${bodyHeight/2 +0.05}" rpy="0.0 0.0 0.0"/>
    </joint>

    <!-- Include pliku Gazebo lidar oraz differential drive controller-->
    <xacro:include filename="$(find robot_model)/urdf/configurations.gazebo.xml"/>
    <xacro:include filename="$(find robot_model)/urdf/lidar.gazebo.xml"/>
    <xacro:include filename="$(find robot_model)/urdf/differential_drive.gazebo.xml"/>

</robot>